on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: test
        run: |
          foo=1
          echo "foo set"
          [[ $foo -eq 1 ]] && exit 0
          echo "exit happened but I still run"
