on:
  push:

jobs:
  build-and-attest:
    runs-on: self-hosted
    permissions:
      contents: read
      attestations: write
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "${{ job.permissions.attestation }}"
