on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ ! startsWith(github.event.head_commit.message, '(HOTFIX)') }}
    steps:
      - uses: actions/checkout@v4
      - name: test
        run: |
          echo "ran"

  test2:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v4
      - run: | 
          echo "ran"
